version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: echomint_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nathan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: echomint
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
